In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
hojas = pd.read_excel( "../data/raw/base-anuario-de-siniestralidad-2024.xlsx",sheet_name=None)
siniestros = hojas["Siniestros"]
vehiculos = hojas["Vehiculos"]
Actor_vial = hojas["Actor_vial"]
Diccionario = hojas["Diccionario"]

# Información 1. Siniestros

En esta sección se realiza la exploración inicial del conjunto de datos de **Siniestros Viales** correspondiente al Anuario de Siniestralidad de Bogotá. El objetivo es comprender la estructura de la información, identificar las variables disponibles, analizar la calidad de los datos y obtener una visión general de los registros que servirán como base para el análisis exploratorio y el desarrollo de modelos predictivos.

In [3]:
# Muestra las primeras 5 filas del DataFrame para conocer la estructura de los datos.
siniestros.head()

,Codigo_Accidente,Formulario,Longitud,Latitud,Direccion,Fecha_Acc,AA_Acc,MM_Acc,DD_Mes_Acc,Dia_Semana_Acc,...,Con_Sitp,Con_Troncal,Con_Alimentador,Con_Zonal,Con_Provisional,Con_Articulado,Con_Biarticulado,Con_Padron_Dual,Con_Servicio_Especial,Con_Taxi
0,4404210,A685,-74.181387,4.621978,AV AVENIDA CIUDAD DE CALI-KR 55 S 02,2015-02-09,2015,Febrero,9,lunes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4404211,A666,-74.027304,4.762901,AK 7-CL 186 02,2015-02-06,2015,Febrero,6,viernes,...,SI,NaN,NaN,SI,NaN,NaN,NaN,NaN,NaN,NaN
2,4404212,A698,-74.053529,4.706939,KR 45-CL 127 02,2015-02-07,2015,Febrero,7,sábado,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4404213,A000042495,-74.099563,4.576256,KR 12-CL 24 S 06,2015-02-09,2015,Febrero,9,lunes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4404214,A644,-74.091667,4.524080,CL 70-KR 11D SE 04,2015-02-08,2015,Febrero,8,domingo,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Devuelve una tupla con el número de filas y columnas (filas, columnas).
siniestros.shape

(278614, 40)

In [5]:
# Obtiene únicamente el número de registros (filas).
siniestros.columns

Index(['Codigo_Accidente', 'Formulario', 'Longitud', 'Latitud', 'Direccion',
       'Fecha_Acc', 'AA_Acc', 'MM_Acc', 'DD_Mes_Acc', 'Dia_Semana_Acc',
       'Hora_Acc', 'Min_Acc', 'Localidad', 'Clase_Acc', 'Elemento_Choque',
       'Tipo_Objeto_Fijo', 'Gravedad_Indicador_Tradicional',
       'Gravedad_indicador_30d', 'Con_Bicicleta', 'Con_Carga',
       'Con_Embriaguez', 'Con_Huecos', 'Con_Menores', 'Con_Moto', 'Con_Peaton',
       'Con_Persona_Mayor', 'Con_Rutas', 'Con_Tpi', 'Con_Tpp', 'Con_Velocidad',
       'Con_Sitp', 'Con_Troncal', 'Con_Alimentador', 'Con_Zonal',
       'Con_Provisional', 'Con_Articulado', 'Con_Biarticulado',
       'Con_Padron_Dual', 'Con_Servicio_Especial', 'Con_Taxi'],
      dtype='str')

In [6]:
# Muestra información general del DataFrame:
# - Número de registros
# - Cantidad de columnas
# - Tipo de dato de cada columna
# - Valores no nulos
# - Uso de memoria
siniestros.info

<bound method DataFrame.info of         Codigo_Accidente  Formulario   Longitud   Latitud  \
0                4404210        A685 -74.181387  4.621978
1                4404211        A666 -74.027304  4.762901
2                4404212        A698 -74.053529  4.706939
3                4404213  A000042495 -74.099563  4.576256
4                4404214        A644 -74.091667  4.524080
...                  ...         ...        ...       ...
278609          10552425  A001344423 -74.140124  4.679552
278610          10552428  A001345144 -74.056021  4.691211
278611          10552453  A001345140 -74.073519  4.651405
278612          10552459  A001343919 -74.149268  4.632396
278613          10552468  A001345254 -74.097915  4.607151

                                   Direccion  Fecha_Acc  AA_Acc   MM_Acc  \
0       AV AVENIDA CIUDAD DE CALI-KR 55 S 02 2015-02-09    2015  Febrero
1                             AK 7-CL 186 02 2015-02-06    2015  Febrero
2                            KR 45-CL 127 02 2015-02-07    2015  Febrero
3                           KR 12-CL 24 S 06 2015-02-09    2015  Febrero
4                         CL 70-KR 11D SE 04 2015-02-08    2015  Febrero
...                                      ...        ...     ...      ...
278609                  CL 26  - KR 103   02 2021-10-08    2021  Octubre
278610                  KR 45  - CL 104   02 2021-10-10    2021  Octubre
278611                   KR 26  - CL 63   02 2021-10-11    2021  Octubre
278612                 DG 6 A  - TV 78 C  02 2021-10-11    2021  Octubre
278613                    KR 30  - CL 6   02 2021-10-11    2021  Octubre

        DD_Mes_Acc Dia_Semana_Acc  ...  Con_Sitp  Con_Troncal Con_Alimentador  \
0                9          lunes  ...       NaN          NaN             NaN
1                6        viernes  ...        SI          NaN             NaN
2                7         sábado  ...       NaN          NaN             NaN
3                9          lunes  ...       NaN          NaN             NaN
4                8        domingo  ...       NaN          NaN             NaN
...            ...            ...  ...       ...          ...             ...
278609           8        viernes  ...        SI          NaN             NaN
278610          10        domingo  ...       NaN          NaN             NaN
278611          11          lunes  ...       NaN          NaN             NaN
278612          11          lunes  ...       NaN          NaN             NaN
278613          11          lunes  ...       NaN          NaN             NaN

       Con_Zonal Con_Provisional Con_Articulado Con_Biarticulado  \
0            NaN             NaN            NaN              NaN
1             SI             NaN            NaN              NaN
2            NaN             NaN            NaN              NaN
3            NaN             NaN            NaN              NaN
4            NaN             NaN            NaN              NaN
...          ...             ...            ...              ...
278609        SI             NaN            NaN              NaN
278610       NaN             NaN            NaN              NaN
278611       NaN             NaN            NaN              NaN
278612       NaN             NaN            NaN              NaN
278613       NaN             NaN            NaN              NaN

       Con_Padron_Dual Con_Servicio_Especial Con_Taxi
0                  NaN                   NaN      NaN
1                  NaN                   NaN      NaN
2                  NaN                   NaN      NaN
3                  NaN                   NaN      NaN
4                  NaN                   NaN      NaN
...                ...                   ...      ...
278609             NaN                   NaN      NaN
278610             NaN                   NaN      NaN
278611             NaN                   NaN      NaN
278612             NaN                   NaN       SI
278613             NaN                   NaN      NaN

[278614 rows x 40 columns]>

In [7]:
# Genera estadísticas descriptivas de las variables numéricas
# (conteo, promedio, desviación estándar, mínimo, máximo, etc.).
siniestros.describe()

,Codigo_Accidente,Longitud,Latitud,Fecha_Acc,AA_Acc,DD_Mes_Acc,Hora_Acc,Min_Acc
count,2.786140e+05,263549.000000,263549.000000,278614,278614.000000,278614.000000,278614.000000,278614.000000
mean,8.055555e+06,-74.105452,4.647105,2019-04-23 22:38:26.520132,2018.803588,15.783920,12.902133,24.677633
min,4.401419e+06,-74.247270,4.043953,2015-01-01 00:00:00,2015.000000,1.000000,0.000000,0.000000
25%,4.472503e+06,-74.135597,4.606198,2017-02-10 00:00:00,2017.000000,8.000000,9.000000,10.000000
50%,1.047282e+07,-74.104129,4.641827,2019-01-13 00:00:00,2019.000000,16.000000,13.000000,28.000000
75%,1.054390e+07,-74.074978,4.688928,2021-07-04 00:00:00,2021.000000,23.000000,17.000000,40.000000
max,1.061630e+07,-74.007000,4.828041,2024-12-31 00:00:00,2024.000000,31.000000,23.000000,59.000000
std,2.983755e+06,0.040043,0.057906,NaN,2.628660,8.777524,5.508462,17.420744

In [8]:
# Cuenta la cantidad de valores nulos en cada columna.
siniestros.isnull().sum()

Codigo_Accidente                       0
Formulario                             0
Longitud                           15065
Latitud                            15065
Direccion                              0
Fecha_Acc                              0
AA_Acc                                 0
MM_Acc                                 0
DD_Mes_Acc                             0
Dia_Semana_Acc                         0
Hora_Acc                               0
Min_Acc                                0
Localidad                              0
Clase_Acc                              0
Elemento_Choque                    44904
Tipo_Objeto_Fijo                  268114
Gravedad_Indicador_Tradicional         0
Gravedad_indicador_30d               148
Con_Bicicleta                     256804
Con_Carga                         241511
Con_Embriaguez                    272688
Con_Huecos                        276298
Con_Menores                       263921
Con_Moto                          194012
Con_Peaton                        245722
Con_Persona_Mayor                 233863
Con_Rutas                         278522
Con_Tpi                           225534
Con_Tpp                           212380
Con_Velocidad                     275997
Con_Sitp                          232309
Con_Troncal                       274299
Con_Alimentador                   274506
Con_Zonal                         243148
Con_Provisional                   275257
Con_Articulado                    276586
Con_Biarticulado                  277408
Con_Padron_Dual                   277482
Con_Servicio_Especial             267901
Con_Taxi                          226323
dtype: int64

In [9]:
# Cuenta el número de registros duplicados.
siniestros.duplicated().sum()

np.int64(0)

# Información 2. Vehículos

En esta sección se realiza la exploración inicial del conjunto de datos de **Vehículos involucrados en siniestros viales** correspondiente al Anuario de Siniestralidad de Bogotá. El objetivo es comprender la estructura de la información, identificar las variables disponibles, analizar la calidad de los datos y caracterizar los tipos de vehículos involucrados en los siniestros, información que será utilizada posteriormente en el Análisis Exploratorio de Datos (EDA) y en la construcción de los modelos predictivos.

In [10]:
 # Muestra las primeras 5 filas del DataFrame para conocer la estructura de los datos.
vehiculos.head()

,Codigo_Accidente,Formulario,Fecha_Acc,AA_Acc,Codigo_Vehiculo,Clase,Servicio,Modalidad,Vehiculo_Viajaba_Clasificado,Tipo_SITP,...,Con_Sitp,Con_Troncal,Con_Alimentador,Con_Zonal,Con_Provisional,Con_Articulado,Con_Biarticulado,Con_Padron_Dual,Con_Servicio_Especial,Con_Taxi
0,4401718,A000040450,2015-01-07,2015,2.0,Motocicleta,Particular,NaN,MOTOCICLETA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4401718,A000040450,2015-01-07,2015,3.0,NaN,Sin información,NaN,SIN INFORMACIÓN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4401726,A000040954,2015-01-07,2015,1.0,Bus,Público,NaN,TRANSPORTE DE PASAJEROS,BIARTICULADO,...,SI,SI,NaN,NaN,NaN,NaN,SI,NaN,NaN,NaN
3,4401725,A000040171,2015-01-07,2015,1.0,Automovil,Particular,NaN,LIVIANO,NaN,...,SI,SI,NaN,NaN,NaN,NaN,NaN,SI,NaN,NaN
4,4401725,A000040171,2015-01-07,2015,2.0,Bus,Público,NaN,TRANSPORTE DE PASAJEROS,PADRON DUAL,...,SI,SI,NaN,NaN,NaN,NaN,NaN,SI,NaN,NaN

In [11]:
 # Devuelve una tupla con el número de filas y columnas (filas, columnas).
vehiculos.shape

(523168, 32)

In [12]:

# Muestra los nombres de las columnas del DataFrame.
vehiculos.columns

Index(['Codigo_Accidente', 'Formulario', 'Fecha_Acc', 'AA_Acc',
       'Codigo_Vehiculo', 'Clase', 'Servicio', 'Modalidad',
       'Vehiculo_Viajaba_Clasificado', 'Tipo_SITP', 'Con_Bicicleta',
       'Con_Carga', 'Con_Embriaguez', 'Con_Huecos', 'Con_Menores', 'Con_Moto',
       'Con_Peaton', 'Con_Persona_Mayor', 'Con_Rutas', 'Con_Tpi', 'Con_Tpp',
       'Con_Velocidad', 'Con_Sitp', 'Con_Troncal', 'Con_Alimentador',
       'Con_Zonal', 'Con_Provisional', 'Con_Articulado', 'Con_Biarticulado',
       'Con_Padron_Dual', 'Con_Servicio_Especial', 'Con_Taxi'],
      dtype='str')

In [13]:
 
# Muestra información general del DataFrame:
# - Número de registros
# - Cantidad de columnas
# - Tipo de dato de cada columna
# - Valores no nulos
# - Uso de memoria
vehiculos.info()

<class 'pandas.DataFrame'>
RangeIndex: 523168 entries, 0 to 523167
Data columns (total 32 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Codigo_Accidente              523168 non-null  int64
 1   Formulario                    523168 non-null  str
 2   Fecha_Acc                     523168 non-null  datetime64[us]
 3   AA_Acc                        523168 non-null  int64
 4   Codigo_Vehiculo               523165 non-null  float64
 5   Clase                         519145 non-null  str
 6   Servicio                      523168 non-null  str
 7   Modalidad                     101939 non-null  str
 8   Vehiculo_Viajaba_Clasificado  523168 non-null  str
 9   Tipo_SITP                     47561 non-null   str
 10  Con_Bicicleta                 43398 non-null   str
 11  Con_Carga                     75182 non-null   str
 12  Con_Embriaguez                11197 non-null   str
 13  Con_Huecos                    3439 non-null    str
 14  Con_Menores                   23427 non-null   str
 15  Con_Moto                      157723 non-null  str
 16  Con_Peaton                    35367 non-null   str
 17  Con_Persona_Mayor             81181 non-null   str
 18  Con_Rutas                     180 non-null     str
 19  Con_Tpi                       108508 non-null  str
 20  Con_Tpp                       124239 non-null  str
 21  Con_Velocidad                 4174 non-null    str
 22  Con_Sitp                      84800 non-null   str
 23  Con_Troncal                   6570 non-null    str
 24  Con_Alimentador               7394 non-null    str
 25  Con_Zonal                     66257 non-null   str
 26  Con_Provisional               6520 non-null    str
 27  Con_Articulado                2904 non-null    str
 28  Con_Biarticulado              1754 non-null    str
 29  Con_Padron_Dual               2027 non-null    str
 30  Con_Servicio_Especial         22029 non-null   str
 31  Con_Taxi                      106940 non-null  str
dtypes: datetime64[us](1), float64(1), int64(2), str(28)
memory usage: 127.7 MB

In [14]:
 # Genera estadísticas descriptivas de las variables numéricas
# (conteo, promedio, desviación estándar, mínimo, máximo, etc.).
vehiculos.describe()

,Codigo_Accidente,Fecha_Acc,AA_Acc,Codigo_Vehiculo
count,5.231680e+05,523168,523168.000000,523165.000000
mean,8.032376e+06,2019-04-09 07:34:39.760229,2018.763512,1.510111
min,4.401419e+06,2015-01-01 00:00:00,2015.000000,1.000000
25%,4.472138e+06,2017-02-07 00:00:00,2017.000000,1.000000
50%,1.047159e+07,2018-12-26 00:00:00,2018.000000,1.000000
75%,1.054193e+07,2021-06-09 00:00:00,2021.000000,2.000000
max,1.061630e+07,2024-12-31 00:00:00,2024.000000,30.000000
std,2.987301e+06,NaN,2.599862,0.626443

In [15]:
 # Cuenta la cantidad de valores nulos en cada columna.
vehiculos.isnull().sum()

Codigo_Accidente                     0
Formulario                           0
Fecha_Acc                            0
AA_Acc                               0
Codigo_Vehiculo                      3
Clase                             4023
Servicio                             0
Modalidad                       421229
Vehiculo_Viajaba_Clasificado         0
Tipo_SITP                       475607
Con_Bicicleta                   479770
Con_Carga                       447986
Con_Embriaguez                  511971
Con_Huecos                      519729
Con_Menores                     499741
Con_Moto                        365445
Con_Peaton                      487801
Con_Persona_Mayor               441987
Con_Rutas                       522988
Con_Tpi                         414660
Con_Tpp                         398929
Con_Velocidad                   518994
Con_Sitp                        438368
Con_Troncal                     516598
Con_Alimentador                 515774
Con_Zonal                       456911
Con_Provisional                 516648
Con_Articulado                  520264
Con_Biarticulado                521414
Con_Padron_Dual                 521141
Con_Servicio_Especial           501139
Con_Taxi                        416228
dtype: int64

In [16]:
 # Cuenta el número de registros duplicados.
vehiculos.duplicated().sum()

np.int64(0)

# Información 3. Actores Viales

En esta sección se realiza la exploración inicial del conjunto de datos de **Actores Viales** involucrados en los siniestros de tránsito registrados en Bogotá. El objetivo es comprender la estructura de la información, identificar las variables disponibles, analizar la calidad de los datos y caracterizar los diferentes tipos de actores viales (peatones, motociclistas, ciclistas, conductores y pasajeros), con el fin de identificar patrones que contribuyan al análisis exploratorio de datos (EDA) y al desarrollo de los modelos predictivos de siniestralidad vial.

In [17]:
# Muestra las primeras 5 filas del DataFrame para conocer la estructura de los datos.
Actor_vial.head()

,Codigo_Accidentado,Codigo_Accidente,Formulario,Codigo_Vehiculo,Ccodigo_Victima,FechaAcc,AnnoAcc,mesAcc,DD_Mes_Acc,Dia_Semana_Acc,...,Con_Sitp,Con_Troncal,Con_Alimentador,Con_Zonal,Con_Provisional,Con_Articulado,Con_Biarticulado,Con_Padron_Dual,Con_Servicio_Especial,Con_Taxi
0,2456665,4403353,A000041152,2.0,0,2015-01-28,2015,Enero,28,miércoles,...,SI,NaN,NaN,SI,NaN,NaN,NaN,NaN,NaN,SI
1,2456666,4403354,A000042570,1.0,0,2015-01-28,2015,Enero,28,miércoles,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2456667,4403354,A000042570,2.0,0,2015-01-28,2015,Enero,28,miércoles,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2456670,4403356,A000042404,1.0,0,2015-01-28,2015,Enero,28,miércoles,...,SI,NaN,NaN,SI,NaN,NaN,NaN,NaN,NaN,NaN
4,2456671,4403356,A000042404,2.0,0,2015-01-28,2015,Enero,28,miércoles,...,SI,NaN,NaN,SI,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
# Devuelve una tupla con el número de filas y columnas (filas, columnas).
Actor_vial.shape

(608155, 44)

In [19]:
# Lista los nombres de todas las columnas del DataFrame.
Actor_vial.columns

Index(['Codigo_Accidentado', 'Codigo_Accidente', 'Formulario',
       'Codigo_Vehiculo', 'Ccodigo_Victima', 'FechaAcc', 'AnnoAcc', 'mesAcc',
       'DD_Mes_Acc', 'Dia_Semana_Acc', 'hourAcc', 'minuAcc', 'Localidad',
       'Edad', 'Sexo', 'Gravedad_Indicador_Tradicional', 'Muerte_Posterior',
       'Fecha_CambioGravedad', 'Gravedad_Indicador_30d', 'Condicion',
       'Condicion_Especifica', 'Tipo_SITP', 'Con_Bicicleta', 'Con_Carga',
       'Con_Embriaguez', 'Con_Huecos', 'Con_Menores', 'Con_Moto', 'Con_Peaton',
       'Con_Persona_Mayor', 'Con_Rutas', 'Con_Tpi', 'Con_Tpp', 'Con_Velocidad',
       'Con_Sitp', 'Con_Troncal', 'Con_Alimentador', 'Con_Zonal',
       'Con_Provisional', 'Con_Articulado', 'Con_Biarticulado',
       'Con_Padron_Dual', 'Con_Servicio_Especial', 'Con_Taxi'],
      dtype='str')

In [20]:

# Muestra información general del DataFrame:
# - Número de registros
# - Cantidad de columnas
# - Tipo de dato de cada columna
# - Valores no nulos
# - Uso de memoria
Actor_vial.info

<bound method DataFrame.info of         Codigo_Accidentado  Codigo_Accidente  Formulario  Codigo_Vehiculo  \
0                  2456665           4403353  A000041152              2.0
1                  2456666           4403354  A000042570              1.0
2                  2456667           4403354  A000042570              2.0
3                  2456670           4403356  A000042404              1.0
4                  2456671           4403356  A000042404              2.0
...                    ...               ...         ...              ...
608150            12850712          10586377  A001518762              2.0
608151            12850713          10586378  A001519586              1.0
608152            12850714          10586378  A001519586              2.0
608153            12850715          10586379  A001517252              1.0
608154            12850719          10586381  A001519732              1.0

        Ccodigo_Victima   FechaAcc  AnnoAcc mesAcc  DD_Mes_Acc Dia_Semana_Acc  \
0                     0 2015-01-28     2015  Enero          28      miércoles
1                     0 2015-01-28     2015  Enero          28      miércoles
2                     0 2015-01-28     2015  Enero          28      miércoles
3                     0 2015-01-28     2015  Enero          28      miércoles
4                     0 2015-01-28     2015  Enero          28      miércoles
...                 ...        ...      ...    ...         ...            ...
608150                1 2023-01-14     2023  Enero          14         sábado
608151                0 2023-01-16     2023  Enero          16          lunes
608152                1 2023-01-16     2023  Enero          16          lunes
608153                0 2023-01-16     2023  Enero          16          lunes
608154                0 2023-01-17     2023  Enero          17         martes

        ...  Con_Sitp  Con_Troncal Con_Alimentador  Con_Zonal Con_Provisional  \
0       ...        SI          NaN             NaN         SI             NaN
1       ...       NaN          NaN             NaN        NaN             NaN
2       ...       NaN          NaN             NaN        NaN             NaN
3       ...        SI          NaN             NaN         SI             NaN
4       ...        SI          NaN             NaN         SI             NaN
...     ...       ...          ...             ...        ...             ...
608150  ...        SI          NaN             NaN         SI             NaN
608151  ...        SI          NaN             NaN         SI             NaN
608152  ...        SI          NaN             NaN         SI             NaN
608153  ...       NaN          NaN             NaN        NaN             NaN
608154  ...       NaN          NaN             NaN        NaN             NaN

       Con_Articulado Con_Biarticulado Con_Padron_Dual Con_Servicio_Especial  \
0                 NaN              NaN             NaN                   NaN
1                 NaN              NaN             NaN                   NaN
2                 NaN              NaN             NaN                   NaN
3                 NaN              NaN             NaN                   NaN
4                 NaN              NaN             NaN                   NaN
...               ...              ...             ...                   ...
608150            NaN              NaN             NaN                   NaN
608151            NaN              NaN             NaN                   NaN
608152            NaN              NaN             NaN                   NaN
608153            NaN              NaN             NaN                   NaN
608154            NaN              NaN             NaN                   NaN

       Con_Taxi
0            SI
1           NaN
2           NaN
3           NaN
4           NaN
...         ...
608150      NaN
608151      NaN
608152      NaN
608153       SI
608154      NaN

[608155 rows x 44 columns]>

In [21]:
# Genera estadísticas descriptivas de las variables numéricas
# (conteo, promedio, desviación estándar, mínimo, máximo, etc.).
Actor_vial.describe()

,Codigo_Accidentado,Codigo_Accidente,Codigo_Vehiculo,Ccodigo_Victima,FechaAcc,AnnoAcc,DD_Mes_Acc,hourAcc,minuAcc,Edad,Fecha_CambioGravedad
count,6.081550e+05,6.081550e+05,595469.000000,608155.000000,608155,608155.000000,608155.000000,608155.000000,608155.000000,594818.000000,1920
mean,8.648353e+06,8.089408e+06,1.442426,0.389809,2019-05-14 07:19:13.949896,2018.858982,15.784164,12.904763,24.758989,37.557703,2019-12-14 14:04:30
min,2.452497e+06,4.401419e+06,0.000000,0.000000,2015-01-01 00:00:00,2015.000000,1.000000,0.000000,0.000000,0.000000,2015-01-10 00:00:00
25%,2.606742e+06,4.473416e+06,1.000000,0.000000,2017-02-18 00:00:00,2017.000000,8.000000,8.000000,10.000000,27.000000,2017-05-06 18:00:00
50%,1.260982e+07,1.047460e+07,1.000000,0.000000,2019-02-01 00:00:00,2019.000000,16.000000,13.000000,29.000000,35.000000,2019-08-22 12:00:00
75%,1.276392e+07,1.054669e+07,2.000000,1.000000,2021-08-08 00:00:00,2021.000000,23.000000,17.000000,40.000000,47.000000,2022-11-05 12:00:00
max,1.292206e+07,1.061630e+07,30.000000,71.000000,2024-12-31 00:00:00,2024.000000,31.000000,23.000000,59.000000,2021.000000,2025-01-30 00:00:00
std,4.981276e+06,2.978044e+06,0.675795,1.337908,NaN,2.660038,8.779040,5.517070,17.414657,14.599189,NaN

In [22]:
# Cuenta la cantidad de valores nulos en cada columna.
Actor_vial.isnull().sum()

Codigo_Accidentado                     0
Codigo_Accidente                       0
Formulario                             0
Codigo_Vehiculo                    12686
Ccodigo_Victima                        0
FechaAcc                               0
AnnoAcc                                0
mesAcc                                 0
DD_Mes_Acc                             0
Dia_Semana_Acc                         0
hourAcc                                0
minuAcc                                0
Localidad                              0
Edad                               13337
Sexo                                5459
Gravedad_Indicador_Tradicional      4435
Muerte_Posterior                  325817
Fecha_CambioGravedad              606235
Gravedad_Indicador_30d              4435
Condicion                              0
Condicion_Especifica                   0
Tipo_SITP                         547619
Con_Bicicleta                     560904
Con_Carga                         528859
Con_Embriaguez                    595430
Con_Huecos                        603891
Con_Menores                       565238
Con_Moto                          415304
Con_Peaton                        534390
Con_Persona_Mayor                 503754
Con_Rutas                         607528
Con_Tpi                           487616
Con_Tpp                           459196
Con_Velocidad                     602144
Con_Sitp                          504302
Con_Troncal                       597132
Con_Alimentador                   599013
Con_Zonal                         529902
Con_Provisional                   600277
Con_Articulado                    602856
Con_Biarticulado                  604643
Con_Padron_Dual                   605567
Con_Servicio_Especial             583929
Con_Taxi                          489349
dtype: int64

In [23]:
# Cuenta el número de registros duplicados.
Actor_vial.duplicated().sum()

np.int64(0)

## Resumen de la estructura de los conjuntos de datos

En esta sección se presenta un resumen general de los conjuntos de datos utilizados en el proyecto. Se identifica la cantidad de registros (filas) y variables (columnas) de cada hoja del archivo fuente, lo que permite dimensionar el volumen de información disponible para el análisis.

Adicionalmente, se revisan los tipos de datos de cada variable con el fin de identificar si corresponden a valores numéricos, categóricos, de texto o de fecha. Esta validación es fundamental para detectar posibles inconsistencias y definir las transformaciones necesarias durante la fase de preparación de los datos.

In [24]:
print(f"Siniestros: {siniestros.shape[0]} filas y {siniestros.shape[1]} columnas")
print(f"Vehículos: {vehiculos.shape[0]} filas y {vehiculos.shape[1]} columnas")
print(f"Actor vial: {Actor_vial.shape[0]} filas y {Actor_vial.shape[1]} columnas")

Siniestros: 278614 filas y 40 columnas
Vehículos: 523168 filas y 32 columnas
Actor vial: 608155 filas y 44 columnas

In [25]:
siniestros.dtypes
vehiculos.dtypes
Actor_vial.dtypes

Codigo_Accidentado                         int64
Codigo_Accidente                           int64
Formulario                                   str
Codigo_Vehiculo                          float64
Ccodigo_Victima                            int64
FechaAcc                          datetime64[us]
AnnoAcc                                    int64
mesAcc                                       str
DD_Mes_Acc                                 int64
Dia_Semana_Acc                               str
hourAcc                                    int64
minuAcc                                    int64
Localidad                                    str
Edad                                     float64
Sexo                                         str
Gravedad_Indicador_Tradicional               str
Muerte_Posterior                             str
Fecha_CambioGravedad              datetime64[us]
Gravedad_Indicador_30d                       str
Condicion                                    str
Condicion_Especifica                         str
Tipo_SITP                                    str
Con_Bicicleta                                str
Con_Carga                                    str
Con_Embriaguez                               str
Con_Huecos                                   str
Con_Menores                                  str
Con_Moto                                     str
Con_Peaton                                   str
Con_Persona_Mayor                            str
Con_Rutas                                    str
Con_Tpi                                      str
Con_Tpp                                      str
Con_Velocidad                                str
Con_Sitp                                     str
Con_Troncal                                  str
Con_Alimentador                              str
Con_Zonal                                    str
Con_Provisional                              str
Con_Articulado                               str
Con_Biarticulado                             str
Con_Padron_Dual                              str
Con_Servicio_Especial                        str
Con_Taxi                                     str
dtype: object